### ISSUE TITLE
Random mineshaft parts in the air

### ISSUE THREAD

**Issue by Koboo** [Astrashh/Aeropelago#1]
Hey, I downloaded this config pack and put it into Terra. Unfortunately I have noticed a strange behavior.

Some information:
* `paper-1.19.2-138.jar` 
* `Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar`
* `AEROPELAGO v0.1.0`

The behavior I have noticed is that a lot of structures are generated under the islands. However, I mean structures that do not hang from the islands by chains, but are randomly generated under the islands, as if they belonged to a vanilla generator.

![2022-09-08_16 07 25](https://user-images.githubusercontent.com/14143908/189144035-e2f2cdd8-ee88-4994-9b31-572144c65ea0.png)
![2022-09-08_16 07 47](https://user-images.githubusercontent.com/14143908/189144041-1c56ae12-f44c-4743-8561-4c64696fa37b.png)
![2022-09-08_16 07 57](https://user-images.githubusercontent.com/14143908/189144047-b772b2b1-be1b-4146-8170-98eff869b7eb.png)

Is this bug possible to fix using the config pack or should this issue be created under the Terra repository?

**Comment by astrsh** [comment]
Structure gen is delegated to vanilla, so you'd disable structure gen either via `server.properties` or through the world manager you're using (refer to the world managers documentation on how to do so). There's no Terra specific enable / disable I know of on 6.2.0
